# -*- coding: utf-8 -*-
"""(Ongoing)240908_gpt_codegeneration_example_v2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kXOx67n--5t1M6Y3NFjCqj32u7Yjx7Mn

# Conclusion

### Scanpy can repeat single task relatively well. It can not generate bug-free code for task planning `trajectory inference` and `batch correction`

### Here are 12 examples for scanpy, including 2 multi task/task planning demo and 10 single task demo. For the remaining demos, the generated code are executed correctly.

### Scanpy

---
### Example1: Batch correction

### Prompt

Provide the python code for batch correction with the API only from Scanpy. Apply it to the built-in pbmc3k processed dataset and pbmc68k reduced dataset

### GPT-4 Turbo Answer:

To perform batch correction on single-cell RNA sequencing data using the Scanpy library, we can employ different approaches, but one common method is to use the "Harmony" integration tool. `scanpy.external.pp.harmony_integrate()` can be useful for batch correction by integrating datasets from different batches. Below is an illustrative Python code to perform batch correction using Scanpy on two datasets: `pbmc3k_processed` (which is assumed here after common preprocessing) and `pbmc68k_reduced` datasets.

First, ensure you have the necessary libraries installed:

```bash
pip install scanpy anndata pandas numpy matplotlib scikit-learn seaborn
pip install harmonypy
```

Now, let's script the batch correction using Harmony through Scanpy:

```python
import scanpy as sc
import scanpy.external as sce

def load_data():
    # Loading example datasets.
    # For real analysis, replace this with reading actual datasets
    adata_pbmc3k = sc.datasets.pbmc3k_processed()  # Processed PBMC 3k dataset
    adata_pbmc68k = sc.datasets.pbmc68k_reduced()  # Reduced PBMC 68k dataset

    # Add batch information for illustrative purposes.
    adata_pbmc3k.obs['batch'] = 'batch1'
    adata_pbmc68k.obs['batch'] = 'batch2'

    # Concatenate the data together for harmony batch correction
    adata = adata_pbmc3k.concatenate(adata_pbmc68k, batch_key='batch')

    return adata

def batch_correct_data(adata):
    # Ensure you have normalized and logged the data before this step, if needed
    sc.pp.log1p(adata)  # if not logged
    sc.pp.scale(adata, max_value=10)  # scaling by maximum value to mitigate extreme values impact

    # Using Harmony for batch correction
    sce.pp.harmony_integrate(adata, key='batch', adjusted_basis='X_pca_harmony')

    return adata

def visualize_results(adata):
    sc.tl.pca(adata, svd_solver='arpack', use_highly_variable=False)
    sc.pp.neighbors(adata, use_rep='X_pca_harmony')  # Using harmony-adjusted PCA
    sc.tl.umap(adata)
    sc.pl.umap(adata, color='batch', title='UMAP after Harmony Integration', save='_harmony_batch_correction.png')

def main():
    adata = load_data()
    adata_corrected = batch_correct_data(adata)
    visualize_results(adata_corrected)

if __name__ == "__main__":
    main()
```

### Explanation:

1. **Data Loading and Concatenation**:
    - We load the `pbmc3k_processed` and `pbmc68k_reduced` datasets. Here it’s presumed they are directly accessible via Scanpy’s dataset functions, which might not be the case outside theoretical or example contexts.
    - Concatenate the datasets indicating that the concat will form distinct batches.

2. **Batch Correction**:
    - We prepare the data by scaling and logging (if needed).
    - Apply Harmony integration (from the scanpy external module) to correct for batch effects, using the batch labels for alignment.

3. **Visualization**:
    - Post-correction visualizations using PCA and UMAP to display the effect of the batch correction.

The function `sce.pp.harmony_integrate()` performs the actual integration (batch correction) work. This function operates assuming that the PCA has been performed on the dataset. Ensure any step relevant specifically to your data condition (like extra preprocessing) is included.

Remember to examine each step and adapt it to your specific datasets and conditions ensuring data compatibility and preprocessing. The provided code assumes direct use without specific compatibility adjustments
"""

!pip install scanpy harmonypy

import scanpy as sc
import scanpy.external as sce

def load_data():
    # Loading example datasets.
    # For real analysis, replace this with reading actual datasets
    adata_pbmc3k = sc.datasets.pbmc3k_processed()  # Processed PBMC 3k dataset
    adata_pbmc68k = sc.datasets.pbmc68k_reduced()  # Reduced PBMC 68k dataset

    # Add batch information for illustrative purposes.
    adata_pbmc3k.obs['batch'] = 'batch1'
    adata_pbmc68k.obs['batch'] = 'batch2'

    # Concatenate the data together for harmony batch correction
    adata = adata_pbmc3k.concatenate(adata_pbmc68k, batch_key='batch')

    return adata

def batch_correct_data(adata):
    # Ensure you have normalized and logged the data before this step, if needed
    sc.pp.log1p(adata)  # if not logged
    sc.pp.scale(adata, max_value=10)  # scaling by maximum value to mitigate extreme values impact

    # Using Harmony for batch correction
    sce.pp.harmony_integrate(adata, key='batch', adjusted_basis='X_pca_harmony')

    return adata

def visualize_results(adata):
    sc.tl.pca(adata, svd_solver='arpack', use_highly_variable=False)
    sc.pp.neighbors(adata, use_rep='X_pca_harmony')  # Using harmony-adjusted PCA
    sc.tl.umap(adata)
    sc.pl.umap(adata, color='batch', title='UMAP after Harmony Integration', save='_harmony_batch_correction.png')

def main():
    adata = load_data()
    adata_corrected = batch_correct_data(adata)
    visualize_results(adata_corrected)

if __name__ == "__main__":
    main()

"""### Note: The generated code raises error `ValueError: Input X contains NaN.` in codeline `sc.tl.pca(adata, svd_solver='arpack')`. This is due to the reason that adata contains nan value and need to be preprocessed. GPT can refer to [github issue](https://github.com/scverse/scanpy/issues/2163) to debug."""



"""---
### Example2: Trajectory inference

### Prompt
Provide the python code for trajectory inference with the API only from Scanpy. Apply it to the built-in pbmc3k processed dataset.
### GPT-4 Turbo Answer:
To perform trajectory inference on single-cell RNA sequencing data using Scanpy, you can utilize the PAGA (Partition-based Graph Abstraction) algorithm, which provides a way to infer paths through the data. The example below uses the `pbmc3k` dataset, which is a standard dataset for demonstration purposes in single-cell RNA sequencing analysis.

First, make sure you have the necessary packages installed. You'll need `scanpy` primarily. You can install it using pip if you don't have it already:

```bash
pip install scanpy
```

Below is the complete Python code, performing basic preprocessing, clustering, computing PAGA, and visualizing the trajectory based on Scanpy's capabilities.

```python
import scanpy as sc

# Load the example dataset
adata = sc.datasets.pbmc3k_processed()

# Basic filtering (if further preprocessing needed, add here)
sc.pp.filter_cells(adata, min_genes=200)
sc.pp.filter_genes(adata, min_cells=3)

# Normalize and log-transform the data
sc.pp.normalize_total(adata, target_sum=1e4)
sc.pp.log1p(adata)

# Identify highly variable genes
sc.pp.highly_variable_genes(adata, min_mean=0.0125, max_mean=3, min_disp=0.5)
adata = adata[:, adata.var['highly_variable']]

# Regress out effects of total counts per cell and the percentage of mitochondrial genes expressed
sc.pp.regress_out(adata, ['total_counts', 'pct_counts_mt'])

# Scale the data to unit variance and zero mean
sc.pp.scale(adata, max_value=10)

# Run PCA to reduce dimensionality
sc.tl.pca(adata, svd_solver='arpack')

# Compute the neighborhood graph
sc.pp.neighbors(adata, n_neighbors=10, n_pcs=40)

# Run UMAP for visualization
sc.tl.umap(adata)

# Run the Louvain algorithm for clustering
sc.tl.louvain(adata)

# Run PAGA to infer trajectories
sc.tl.paga(adata, groups='louvain')
sc.pl.paga(adata, color=['louvain'])

# Optionally compute a UMAP initialized with the PAGA-initialized positions
sc.tl.umap(adata, init_pos='paga')
sc.pl.umap(adata, color='louvain')

# Show the plot
adata.write(results_file)
```

In this code:

1. Data is loaded using Scanpy's built-in function (`sc.datasets.pbmc3k_processed()`).
2. Data is filtered by cells and genes to ensure robust analysis.
3. Normalization and log transformation are applied so that gene expression levels across cells can be more comparable.
4. Highly variable genes are identified to focus the analysis on genes that contribute most to variability among cells.
5. Linear regressions correct for confounding factors (total counts and mitochondrial gene expression).
6. PCA (Principal Component Analysis) is used for dimensionality reduction—a standard step in scRNA-seq analysis.
7. A neighborhood graph is computed to reflect the relationships (similarity) between cells.
8. The Louvain algorithm clusters the cells.
9. PAGA is used to infer and visualize the developmental trajectories among the discovered cell states (clusters).
10. Visualization is performed using UMAP, with PAGA paths overlayed to guide the initialization of UMAP coordinates, offering insightful perspectives on the data structure.

This approach provides a trajectory analysis of single-cell RNA data, inferring possible developmental pathways and relationships among cell types based on gene expression profiles. Adjustments might be necessary based on more specific needs or data characteristics.

"""

import scanpy as sc

# Load the example dataset
adata = sc.datasets.pbmc3k_processed()

# Basic filtering (if further preprocessing needed, add here)
sc.pp.filter_cells(adata, min_genes=200)
sc.pp.filter_genes(adata, min_cells=3)
print(adata)

# Normalize and log-transform the data
sc.pp.normalize_total(adata, target_sum=1e4)
sc.pp.log1p(adata)

# Identify highly variable genes
sc.pp.highly_variable_genes(adata, min_mean=0.0125, max_mean=3, min_disp=0.5)
adata = adata[:, adata.var['highly_variable']]

# Regress out effects of total counts per cell and the percentage of mitochondrial genes expressed
sc.pp.regress_out(adata, ['total_counts', 'pct_counts_mt'])

# Scale the data to unit variance and zero mean
sc.pp.scale(adata, max_value=10)

# Run PCA to reduce dimensionality
sc.tl.pca(adata, svd_solver='arpack')

# Compute the neighborhood graph
sc.pp.neighbors(adata, n_neighbors=10, n_pcs=40)

# Run UMAP for visualization
sc.tl.umap(adata)

# Run the Louvain algorithm for clustering
sc.tl.louvain(adata)

# Run PAGA to infer trajectories
sc.tl.paga(adata, groups='louvain')
sc.pl.paga(adata, color=['louvain'])

# Optionally compute a UMAP initialized with the PAGA-initialized positions
sc.tl.umap(adata, init_pos='paga')
sc.pl.umap(adata, color='louvain')

# Show the plot
adata.write(results_file)

"""### Note: API `scanpy.pp.highly_variable_genes` will raise error `TypeError: putmask: first argument must be an array` for some dataset `pbmc3k_processed`, while other dataset `pbmc3k` will not. This is also an [open issue](https://github.com/scverse/scanpy/issues/3070) submitted by other users."""



"""### Example3: Gene ranking

### Prompt

Provide the python code for plotting the ranking of genes with the API only from Scanpy. Apply it to the built-in pbmc3k processed dataset.[link text](https://)

### GPT-4 Turbo Answer

Below is a Python example that uses Scanpy to process the `pbmc3k` dataset and then plots the gene rankings. This example first preprocesses the data (for normalization and selection of highly variable genes) and then ranks the genes based on their scores using PCA as part of the analysis. Finally, the gene rankings are plotted using `sc.pl.rank_genes_groups`. Here are the steps outlined:

1. Load the necessary libraries.
2. Load the example dataset.
3. Preprocess the data (normalization, logarithmic transformation, identifying highly variable genes).
4. Perform PCA to find the principal components.
5. Cluster the cells.
6. Find marker genes for each cluster.
7. Plot the ranking of genes.

Ensure that Scanpy and its dependencies are properly installed in your Python environment. You can install Scanpy using pip:

```bash
pip install scanpy
```

Here's the code:

```python
import scanpy as sc

# Load the example dataset
adata = sc.datasets.pbmc3k_processed()

# Normalization step (if necessary)
sc.pp.normalize_total(adata, target_sum=1e4)
sc.pp.log1p(adata)

# Identify highly variable genes (if not yet done)
sc.pp.highly_variable_genes(adata, min_mean=0.0125, max_mean=3, min_disp=0.5)

# Re-run the PCA and clustering after identifying highly variable genes
adata = adata[:, adata.var.highly_variable]
sc.tl.pca(adata, svd_solver='arpack')

# Clustering the data
sc.pp.neighbors(adata)
sc.tl.leiden(adata)

# Find marker genes
sc.tl.rank_genes_groups(adata, 'leiden', method='t-test')

# Plot ranking of marker genes for each cluster
sc.pl.rank_genes_groups(adata, n_genes=20, sharey=False)
```

### Notes:
- The `sc.datasets.pbmc3k_processed()` method fetches a dataset that has been preprocessed already, which includes normalization and the identification of highly variable genes. Some steps above are repeated for educational purposes and might not affect the pre-processed dataset.
- Adjust the clustering, PCA, and marker gene detection based on the specific analysis needs and the characteristics of the dataset.
- The number of genes (`n_genes`) shown in the plot can be adjusted.

This code will provide a visual representation of the top differentially expressed genes across the identified clusters, which can help in understanding the biological heterogeneity of the cell population. Adjust parameters and steps based on your specific analysis requirements and to dive deeper into specific aspects of the dataset.
"""

!pip install igraph leidenalg louvain

import scanpy as sc

# Load the example dataset
adata = sc.datasets.pbmc3k_processed()

# Normalization step (if necessary)
sc.pp.normalize_total(adata, target_sum=1e4)
sc.pp.log1p(adata)

# Identify highly variable genes (if not yet done)
sc.pp.highly_variable_genes(adata, min_mean=0.0125, max_mean=3, min_disp=0.5)

# Re-run the PCA and clustering after identifying highly variable genes
adata = adata[:, adata.var.highly_variable]
sc.tl.pca(adata, svd_solver='arpack')

# Clustering the data
sc.pp.neighbors(adata)
sc.tl.leiden(adata)

# Find marker genes
sc.tl.rank_genes_groups(adata, 'leiden', method='t-test')

# Plot ranking of marker genes for each cluster
sc.pl.rank_genes_groups(adata, n_genes=20, sharey=False)

"""### Note: when the targeted task requires more pre-request steps, it has higher probability to generate error. It meets the same error `TypeError: putmask: first argument must be an array` as we met before.

---
### Example4: Violin visualization

### Prompt

Provide the python code for visualizing the genes expression values through violin figure with the API only from Scanpy. Apply it to the built-in pbmc3k processed dataset.

### GPT-4 Turbo Answer

To visualize gene expression values using a violin plot in Scanpy, you'll need to import the library and load a standard processed dataset. Below is detailed Python code that uses Scanpy to visualize gene expression in a violin plot from the built-in pbmc3k dataset.

First, ensure you have installed Scanpy and other necessary libraries, like pandas and numpy. If you haven't installed these packages yet, you can install them via pip:

```bash
pip install scanpy pandas numpy matplotlib
```

Now, here's a step-by-step Python script to visualize gene expression using a violin plot:

```python
import scanpy as sc
import pandas as pd

def main():
    # Load the example pbmc3k dataset from Scanpy datasets
    adata = sc.datasets.pbmc3k_processed()

    # Check the data (optional)
    print(adata)

    # Normalize data to ensure meaningful visualization
    sc.pp.normalize_total(adata, target_sum=1e4)
    sc.pp.log1p(adata)

    # Choose a list of genes you want to visualize.
    # For demonstration, let's arbitrarily pick some typical immune cell markers.
    genes_to_plot = ['CD3D', 'CD3E', 'CD19', 'CD34', 'LYZ']  # Adjust the list based on your focus.

    # Visualize the expression of these genes using violin plot
    sc.pl.violin(adata, keys=genes_to_plot, jitter=True)

main()
```

### Description of Steps

1. **Import necessary libraries**: Import Scanpy as well as other dependencies.
2. **Loading the Data**: The `sc.datasets.pbmc3k_processed()` function fetches the preprocessed dataset having 3k PBMCs from 10X Genomics.
3. **Normalize the data**: Before visualization, normalization is performed to scale the data keeping the relative differences in gene expression values intact.
4. **Gene Selection**: Define genes you are interested in. Replace `'CD3D', 'CD3E', 'CD19', 'CD34', 'LYZ'` with other genes of interest as required.
5. **Violin Plot Visualization**: Use `sc.pl.violin()` from Scanpy to create violin plots of these genes to observe their expression profiles in the dataset.
6. **Jitter**: Enabled jitter to better visualize individual data points.

### Considerations
- **Gene Names**: Ensure that gene names used in the plots are correct and they exist in the dataset. You can check available genes via `adata.var_names`.
- **Additional Adjustments**: Depending on your specific requirements or dataset, you might need additional preprocessing steps, or you might want to adjust the layout or aesthetics of the plot.

This code provides a basic outline and can be modified based on further specifications of the analysis or visual requirements.
"""

import scanpy as sc
import pandas as pd

def main():
    # Load the example pbmc3k dataset from Scanpy datasets
    adata = sc.datasets.pbmc3k_processed()

    # Check the data (optional)
    print(adata)

    # Normalize data to ensure meaningful visualization
    sc.pp.normalize_total(adata, target_sum=1e4)
    sc.pp.log1p(adata)

    # Choose a list of genes you want to visualize.
    # For demonstration, let's arbitrarily pick some typical immune cell markers.
    genes_to_plot = ['CD3D', 'CD3E', 'CD19', 'CD34', 'LYZ']  # Adjust the list based on your focus.

    # Visualize the expression of these genes using violin plot
    sc.pl.violin(adata, keys=genes_to_plot, jitter=True)

main()

"""### Note: the generated code raises error `KeyError: "Could not find keys '['CD34']' in columns of `adata.obs` or in adata.raw.var_names."`. Because it didn't know which attribute is indeed exist in the adata object."""



"""### Example5: Quality control

To calculate quality control metrics for single-cell RNA sequencing data using Scanpy, and applying it to the built-in pbmc3k dataset, you can follow these steps in Python. First, ensure you have Scanpy installed. If not, you can install it using pip:

```bash
pip install scanpy
```

Next, you can load the PBMC 3k dataset directly from Scanpy, calculate the quality control metrics, plot them, and filter cells based on these metrics. Here is how you can do it:

```python
import scanpy as sc

# Load the pbmc3k dataset
adata = sc.datasets.pbmc3k_processed()

# Calculate QC metrics
adata.var['mito'] = adata.var_names.str.startswith('MT-')  # Assuming mitochondrial genes are prefixed by 'MT-'
sc.pp.calculate_qc_metrics(adata, qc_vars=['mito'], percent_top=None, log1p=False, inplace=True)

# Visualizing QC metrics
sc.pl.violin(adata, ['n_genes_by_counts', 'total_counts', 'pct_counts_mito'],
             jitter=0.4, multi_panel=True)

# Filtering cells
sc.pp.filter_cells(adata, min_genes=200)
sc.pp.filter_cells(adata, max_counts=25000)
sc.pp.filter_genes(adata, min_cells=3)

# Recalculate metrics post filtering
adata.var['mito'] = adata.var_names.str.startswith('MT-')
sc.pp.calculate_qc_metrics(adata, qc_vars=['mito'], percent_top=None, log1p=False, inplace=True)

# Plotting the QC metrics again post-filtering
sc.pl.violin(adata, ['n_genes_by_counts', 'total_counts', 'pct_counts_mito'],
             jitter=0.4, multi_panel=True)

# Show the filtered data
print(adata)
```

### Explanation:

1. **Loading the Data**: `sc.datasets.pbmc3k_processed()` loads a preprocessed dataset of PBMC (Peripheral Blood Mononuclear Cells) obtained from 10X Genomics. The dataset is already normalized and log-transformed.

2. **Calculate QC Metrics**: We're adding a column to locate mitochondrial genes (commonly used as a quality control metric in single-cell data). Using `scanpy.pp.calculate_qc_metrics`, we compute the number of genes expressed, total counts, and percentage of mitochondrial genes for each cell.

3. **Visualizing QC Metrics**: Using `scanpy.pl.violin`, we plot these metrics to visualize potential outliers and get a sense of the overall data quality.

4. **Filtering Data**: We filter out cells with fewer than 200 detected genes or more than 25,000 total counts to remove low-quality cells. This step may need adjustments based on specific datasets or research requirements.

5. **Recalculation and Revisualization Post Filtering**: After filtering the dataset, it's a good practice to recalculate and plot QC metrics again to confirm the data's quality has improved and check the effect of the filtering.

The steps above provide a basic framework for applying QC metrics using Scanpy to a single-cell RNA sequencing dataset. Adjustments may be needed depending on specific data characteristics or research requirements.
"""

import scanpy as sc

# Load the pbmc3k dataset
adata = sc.datasets.pbmc3k_processed()
print(adata)

# Calculate QC metrics
adata.var['mito'] = adata.var_names.str.startswith('MT-')  # Assuming mitochondrial genes are prefixed by 'MT-'
sc.pp.calculate_qc_metrics(adata, qc_vars=['mito'], percent_top=None, log1p=False, inplace=True)

# Visualizing QC metrics
sc.pl.violin(adata, ['n_genes_by_counts', 'total_counts', 'pct_counts_mito'],
             jitter=0.4, multi_panel=True)

# Filtering cells
sc.pp.filter_cells(adata, min_genes=200)
print(adata)
sc.pp.filter_cells(adata, max_counts=25000)
print(adata)
sc.pp.filter_genes(adata, min_cells=3)
print(adata)

# Recalculate metrics post filtering
adata.var['mito'] = adata.var_names.str.startswith('MT-')
sc.pp.calculate_qc_metrics(adata, qc_vars=['mito'], percent_top=None, log1p=False, inplace=True)

# Plotting the QC metrics again post-filtering
sc.pl.violin(adata, ['n_genes_by_counts', 'total_counts', 'pct_counts_mito'],
             jitter=0.4, multi_panel=True)

# Show the filtered data
print(adata)

"""### Note: the generated code didn't get raised error, but the preprocessing steps as `sc.pp.filter_cells(adata, max_counts=25000)` shows that nothing is filtered. The parameters predicted by gpt might not be reasonable enough to filter out the data.

---
### Example6: Heatmap visualization


### Prompt

Provide the python code for visualizing the genes expression values through heatmap with the API only from Scanpy. Apply it to the built-in pbmc3k processed dataset.

### GPT-4 Turbo Answer:

To visualize gene expression values as a heatmap in Python using the Scanpy API, first, you'll need to install the Scanpy library if it's not already installed in your Python environment. Scanpy is a popular library for analyzing single-cell RNA sequencing data, which includes functions to preprocess data, perform clustering, and visualize results including generating heatmaps.

Here is how you could do it, step by step, including loading a built-in dataset (such as the `pbmc3k_processed` dataset), selecting genes, and plotting a heatmap.

```python
import scanpy as sc

# First, you will need to load the dataset. If you do not have it,
# you can download and load it directly from the scanpy datasets.
adata = sc.datasets.pbmc3k_processed()

# Normally at this stage, the data should already be preprocessed,
# so we can directly use the data for visualization.

# Select a subset of genes for visualization, for example
genes_of_interest = ['IL7R', 'CD79A', 'CD3D', 'CD14', 'LYZ']

# Ensure the genes are in the expression matrix
adata_subset = adata[:, adata.var_names.isin(genes_of_interest)]

# Create the heatmap for the selected genes.
sc.pl.heatmap(adata_subset, var_names=genes_of_interest, groupby='louvain', cmap='viridis', dendrogram=True)

# save plot if needed
# plt.savefig('heatmap.png')
```

Here's the detailed explanation of what the code does:

1. We import the necessary library, `scanpy`.
2. We load the `pbmc3k_processed` dataset. This dataset is often used as a benchmark in single-cell RNA-seq analyses and comes preprocessed (i.e., normalized, log-transformed, etc.).
3. We specify a list of gene names that we are particularly interested in. This must be based on the biological question you wish to explore.
4. We use a subset of the `adata` object that only includes the selected genes to make the heatmap more informative and focused.
5. We create a heatmap using `scanpy.pl.heatmap`. The `groupby` parameter is set to 'louvain', which refers to the Louvain community detection method used in the clustering step of processing this dataset. `cmap` 'viridis' can be replaced with other colormap names depending on preference.
6. Optional: You can save the plot as an image file using matplotlib's `savefig()`.

This should give you a clear heatmap of how the selected genes are expressed across the computed Louvain clusters in the provided single-cell dataset.
"""

import scanpy as sc

# First, you will need to load the dataset. If you do not have it,
# you can download and load it directly from the scanpy datasets.
adata = sc.datasets.pbmc3k_processed()
print(adata)

# Normally at this stage, the data should already be preprocessed,
# so we can directly use the data for visualization.

# Select a subset of genes for visualization, for example
genes_of_interest = ['IL7R', 'CD79A', 'CD3D', 'CD14', 'LYZ']

# Ensure the genes are in the expression matrix
adata_subset = adata[:, adata.var_names.isin(genes_of_interest)]
print(adata_subset)

# Create the heatmap for the selected genes.
sc.pl.heatmap(adata_subset, var_names=genes_of_interest, groupby='louvain', cmap='viridis', dendrogram=True)

# save plot if needed
# plt.savefig('heatmap.png')

"""### Note: The generated code raises error `ValueError: Distance matrix 'X' must be symmetric.`. This code works without preprocessing step `adata_subset = adata[:, adata.var_names.isin(genes_of_interest)]`, which means gpt don't know the constraint on input of the API `scanpy.pl.heatmap`. Also, the preprocessing step of gpt generated code is not reasonable as it filters out almost all cells while only remaining one cell `CD79A`"""

adata_subset.var

"""---
### Example7: Moran's I metric


### Prompt

Provide the python code for computing Moran’s I metric of the data with the API only from Scanpy. Apply it to the built-in pbmc3k processed dataset.

### GPT-4 Turbo Answer:

To compute Moran’s I metric using Python, specifically within the context of single-cell RNA sequencing data, we will use the Scanpy library. Moran's I is a measure of spatial autocorrelation which, in the context of single-cell data, can provide insights into the spatial arrangements or patterns of gene expression.

First, if you haven't already installed Scanpy, you can install it using pip:

```bash
pip install scanpy
```

Below is a step-by-step Python code on how to load the pbmc3k dataset, preprocess it, compute Moran's I for a gene, and visualize it. Note that Moran's I itself is not directly included in Scanpy's standard functions but can be computed using the `scanpy.metrics.moran_i` function provided you have an adequate spatial dataset. For demonstration, we'll treat the `pbmc3k` dataset as if it has spatial data by creating some mock spatial data.

```python
import scanpy as sc
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

# Load the example dataset
adata = sc.datasets.pbmc3k_processed()

# Normally, Moran's I requires a spatial dataset. Since pbmc3k isn't inherently spatial,
# we fabricate some spatial coordinates for demonstration purposes. In real scenarios,
# you would use actual spatial coordinates associated with the cells.
np.random.seed(42)
adata.obs['x_coord'] = np.random.rand(adata.n_obs)
adata.obs['y_coord'] = np.random.rand(adata.n_obs)

# Create a spatial neighbors graph, assuming it's based on the mock coordinates
sc.pp.neighbors(adata, use_rep='X_pca', key_added='spatial_neighbors', n_neighbors=10)
sc.tl.draw_graph(adata, key_added='spatial_neighbors_draw_graph')

# Choose a gene to calculate Moran's I statistic, for instance 'CST3'
gene_expression = adata[:, 'CST3'].X
if scipy.sparse.issparse(gene_expression):
    gene_expression = gene_expression.toarray().flatten()

# Since spatial data like coordinates are needed (and we've fabricated some), we calculate Moran's I
import geopandas as gpd
from libpysal.weights import DistanceBand
from esda.moran import Moran

# Create a GeoDataFrame for using spatial analysis tools
gdf = gpd.GeoDataFrame(adata.obs, geometry=gpd.points_from_xy(adata.obs.x_coord, adata.obs.y_coord))

# Create a spatial weights matrix using a threshold distance
# Note: This value of distance (like 0.2 here) should ideally be based on your dataset's actual spatial context.
w = DistanceBand.from_dataframe(gdf, threshold=0.2, binary=True, silence_warnings=True)

# Compute Moran's I
moran_i = Moran(gene_expression, w)
print('Moran’s I:', moran_i.I, 'P-value:', moran_i.p_sim)

# Visualization of the gene expression with the coordinates to visualize possible spatial autocorrelation
plt.scatter(adata.obs['x_coord'], adata.obs['y_coord'], c=gene_expression, cmap='viridis', s=50)
plt.colorbar(label='Expression level of CST3')
plt.title('Spatial Distribution of CST3 Expression')
plt.xlabel('X Coordinate')
plt.ylabel('Y Coordinate')
plt.show()
```

In this example, the Moran’s I statistic would be calculated using mocked spatial data. Note that genuine spatial data (from experiments like spatial transcriptomics) should be used for meaningful biological insights. The visualization provides a mock view on how gene expression patterns might look in a spatial data context. Adjust the threshold and methods as per your actual spatial data and experiment needs.
"""

import scanpy as sc
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

# Load the example dataset
adata = sc.datasets.pbmc3k_processed()

# Normally, Moran's I requires a spatial dataset. Since pbmc3k isn't inherently spatial,
# we fabricate some spatial coordinates for demonstration purposes. In real scenarios,
# you would use actual spatial coordinates associated with the cells.
np.random.seed(42)
adata.obs['x_coord'] = np.random.rand(adata.n_obs)
adata.obs['y_coord'] = np.random.rand(adata.n_obs)

# Create a spatial neighbors graph, assuming it's based on the mock coordinates
sc.pp.neighbors(adata, use_rep='X_pca', key_added='spatial_neighbors', n_neighbors=10)
sc.tl.draw_graph(adata, key_added='spatial_neighbors_draw_graph')

# Choose a gene to calculate Moran's I statistic, for instance 'CST3'
gene_expression = adata[:, 'CST3'].X
if scipy.sparse.issparse(gene_expression):
    gene_expression = gene_expression.toarray().flatten()

# Since spatial data like coordinates are needed (and we've fabricated some), we calculate Moran's I
import geopandas as gpd
from libpysal.weights import DistanceBand
from esda.moran import Moran

# Create a GeoDataFrame for using spatial analysis tools
gdf = gpd.GeoDataFrame(adata.obs, geometry=gpd.points_from_xy(adata.obs.x_coord, adata.obs.y_coord))

# Create a spatial weights matrix using a threshold distance
# Note: This value of distance (like 0.2 here) should ideally be based on your dataset's actual spatial context.
w = DistanceBand.from_dataframe(gdf, threshold=0.2, binary=True, silence_warnings=True)

# Compute Moran's I
moran_i = Moran(gene_expression, w)
print('Moran’s I:', moran_i.I, 'P-value:', moran_i.p_sim)

# Visualization of the gene expression with the coordinates to visualize possible spatial autocorrelation
plt.scatter(adata.obs['x_coord'], adata.obs['y_coord'], c=gene_expression, cmap='viridis', s=50)
plt.colorbar(label='Expression level of CST3')
plt.title('Spatial Distribution of CST3 Expression')
plt.xlabel('X Coordinate')
plt.ylabel('Y Coordinate')
plt.show()

"""### Note: The generated code has two issues. The first issue is that it assumes `key_added` is the parameter of scanpy.tl.draw_graph, while it is not. As a result, it raises error `TypeError: 'key_added' is an invalid keyword argument for this function`. Another issue is that it uses `Moran` function from external library `esda.moran` instead of calling its API `scanpy.metrics.morans_i`. This API exist in [1.8.x version of scanpy](https://scanpy.readthedocs.io/en/1.8.x/generated/scanpy.metrics.morans_i.html), which is [released](https://pypi.org/project/scanpy/\#history) before Apr 1, 2022. So this API should be recognized by GPT."""



"""---
### Example8: Cell density embedding

### Prompt

Provide the python code for plotting the density of cells in umap embedding with the API only from Scanpy. Apply it to the built-in pbmc3k processed dataset.

### GPT-4 Turbo Answer:
To plot the density of cells in UMAP embedding using the Scanpy library and applying it to the built-in pbmc3k dataset, you first need to install Scanpy if you haven't done so yet. You can install it via pip:

```bash
pip install scanpy
```

Now, here's the Python code that will load the pbmc3k dataset, perform the necessary preprocessing, compute the UMAP embedding, and plot the density of cells on the UMAP plots.

```python
import scanpy as sc

# Load PBMC 3k dataset from Scanpy's datasets
adata = sc.datasets.pbmc3k_processed()

# Check if the UMAP has been computed, if not compute it
if 'X_umap' not in adata.obsm.keys():
    sc.pp.neighbors(adata)  # Compute the neighborhood graph
    sc.tl.umap(adata)       # Compute UMAP

# Plot UMAP with the density of cells
sc.pl.umap(adata, color='louvain', use_raw=False, density=True, legend_loc='on data')

```

Explanation of code:
- The dataset `pbmc3k_processed` is preprocessed, meaning it includes PCA results and some clustering (usually stored in adata.obs).
- Before plotting, it checks if UMAP embeddings (`X_umap`) are already in the AnnData object (`adata`). If they are not, it computes a neighborhood graph and then UMAP embeddings.
- The `sc.pl.umap()` function from Scanpy is used with `density=True` to plot cell densities, `color='louvain'` to color cells by their Louvain cluster, and `use_raw=False` to indicate that the UMAP should be plotted using processed data.

This will create a UMAP visualization color-coded by Louvain clusters, overlayed with a density plot that highlights areas with higher cell concentrations. Ensure that `legend_loc='on data'` to add cluster identifiers directly on the plot for better visual cues of cluster locations in high-density regions.
"""

import scanpy as sc

# Load PBMC 3k dataset from Scanpy's datasets
adata = sc.datasets.pbmc3k_processed()

# Check if the UMAP has been computed, if not compute it
if 'X_umap' not in adata.obsm.keys():
    sc.pp.neighbors(adata)  # Compute the neighborhood graph
    sc.tl.umap(adata)       # Compute UMAP

# Plot UMAP with the density of cells
sc.pl.umap(adata, color='louvain', use_raw=False, density=True, legend_loc='on data')

"""### Note: the generated code raises an error `AttributeError: PathCollection.set() got an unexpected keyword argument 'density'`, which indicates that the API `scanpy.pl.umap` should not treat `density` as its parameters.

### Example9: Hierarchically-clustered heatmap


### Prompt

Provide the python code for drawing a hierarchically clustered heatmap with the API only from Scanpy. Apply it to the built-in pbmc3k processed dataset.

### GPT-4 Turbo Answer:

To draw a hierarchically clustered heatmap using the Scanpy library, you can follow these steps involving loading the built-in `pbmc3k` dataset, performing necessary preprocessing, and finally plotting the heatmap. Below is the complete Python code to achieve this.

1. Import necessary libraries.
2. Load the dataset.
3. Preprocess the data (normalization, log transformation, detecting highly variable genes).
4. Perform PCA for dimensionality reduction.
5. Compute the neighborhood graph.
6. Cluster the data.
7. Identify marker genes.
8. Plot heatmap with hierarchical clustering.

```python
import scanpy as sc

# 1. Load the example dataset.
adata = sc.datasets.pbmc3k_processed()

# 2. Preprocessing steps would typically involve normalization and scaling,
# but since we are using a processed dataset, we can move directly to clustering.

# Optional: Basic preprocessing if starting with a raw dataset
# sc.pp.normalize_per_cell(adata, counts_per_cell_after=1e4)
# sc.pp.log1p(adata)
# sc.pp.highly_variable_genes(adata, n_top_genes=2000)
# adata = adata[:, adata.var['highly_variable']]

# 3. Run PCA for dimensionality reduction
sc.tl.pca(adata, svd_solver='arpack')

# 4. Compute the neighborhood graph
sc.pp.neighbors(adata, n_neighbors=10, n_pcs=40)

# 5. Find clusters
sc.tl.leiden(adata)

# 6. Run UMAP (not necessary but useful for visualization)
sc.tl.umap(adata)

# 7. Find marker genes to distinguish clusters
sc.tl.rank_genes_groups(adata, 'leiden', method='t-test')
sc.pl.rank_genes_groups(adata, n_genes=25, sharey=False)

# 8. Draw the heatmap for the marker genes of each cluster
sc.pl.matrixplot(adata, var_names=adata.raw.var_names,
                 groupby='leiden', dendrogram=True, cmap='viridis',
                 standard_scale='var', save=True)
```

### Explanation of the key steps:
- **Load Data**: Here we're using the `pbmc3k_processed` dataset provided by Scanpy.
- **Preprocessing**: This would typically involve normalization, logarithmic transformation, and selection of highly variable genes. Since we are using a processed version of the dataset, these steps may already be done.
- **PCA**: Principal component analysis reduces the dimensionality of the data, retaining essential features.
- **Neighbors Computation**: To understand the local structure of the data, a neighborhood graph is computed.
- **Clustering**: The Leiden algorithm identifies relatively densely connected groups of cells.
- **Marker Genes**: Identifying marker genes helps in understanding the defining characteristics of each cluster.
- **UMAP**: A visualization tool to represent the data in a low-dimensional space. Useful for examining how clusters from step 5 arrange spatially.
- **MatrixPlot**: This function can be used to create a heatmap of gene expression, with options for hierarchical clustering of rows (genes) and columns (samples/groups).

This pipeline will result in a heatmap where you can observe clusters of cells based on their expression profiles and hierarchical groupings both of samples and genes. Note that "dendrogram=True" in `matrixplot` function enables hierarchical clustering based on the data. Adjust the `var_names` parameter to focus on specific genes or use the results from `rank_genes_groups` to explore markers for each cluster.

Ensure you have an adequate version of Scanpy installed that supports all function calls (usually Scanpy >=1.4).
"""

import scanpy as sc

# 1. Load the example dataset.
adata = sc.datasets.pbmc3k_processed()

# 2. Preprocessing steps would typically involve normalization and scaling,
# but since we are using a processed dataset, we can move directly to clustering.

# Optional: Basic preprocessing if starting with a raw dataset
# sc.pp.normalize_per_cell(adata, counts_per_cell_after=1e4)
# sc.pp.log1p(adata)
# sc.pp.highly_variable_genes(adata, n_top_genes=2000)
# adata = adata[:, adata.var['highly_variable']]

# 3. Run PCA for dimensionality reduction
sc.tl.pca(adata, svd_solver='arpack')

# 4. Compute the neighborhood graph
sc.pp.neighbors(adata, n_neighbors=10, n_pcs=40)

# 5. Find clusters
sc.tl.leiden(adata)

# 6. Run UMAP (not necessary but useful for visualization)
sc.tl.umap(adata)

# 7. Find marker genes to distinguish clusters
sc.tl.rank_genes_groups(adata, 'leiden', method='t-test')
sc.pl.rank_genes_groups(adata, n_genes=25, sharey=False)

# 8. Draw the heatmap for the marker genes of each cluster
sc.pl.matrixplot(adata, var_names=adata.raw.var_names,
                 groupby='leiden', dendrogram=True, cmap='viridis',
                 standard_scale='var', save=True)

"""### Note: There are three issues about the gpt-generated code. one is that it didn't use `scanpy.pl.clustermap`, which already been [developed](https://scanpy.readthedocs.io/en/1.8.x/generated/scanpy.pl.clustermap.html) in 1.8.x version. Another issue is that it raises error `ValueError: Image size of 507648x380 pixels is too large. It must be less than 2^16 in each direction.`, which might indicate that the data need some preprocessing (like filtering). The last one is its optional preprocessing codes which are commented. This code raises error for `TypeError: putmask: first argument must be an array` when it calls `sc.pp.highly_variable_genes(adata, n_top_genes=2000)`.

---
### Example10: Dotplot visualization

### Prompt

Provide the python code for visualizing the genes expression values through dotplot with the API only from Scanpy. Apply it to the built-in pbmc3k processed dataset.

### GPT-4 Turbo Answer:

To visualize gene expression data using a dotplot from the Scanpy API, and especially applying this visualization on the built-in `pbmc3k_processed` dataset, you should follow these steps. The steps include loading the necessary data, preprocessing if needed, and finally plotting the data using the `sc.pl.dotplot` function from Scanpy. Below is a detailed Python script example that demonstrates how to achieve this:

1. **Import necessary libraries**
2. **Load the dataset**
3. **Preprocess data** (if required, for example, normalize or identify highly variable genes)
4. **Plot the data using a dotplot**

First, ensure you have the `scanpy` package installed. You can install it using pip if it's not installed:

```bash
pip install scanpy
```

Here is a comprehensive Python script:

```python
import scanpy as sc

# Load the example dataset
adata = sc.datasets.pbmc3k_processed()

# Typically preprocessing would be done here, but since we're using a processed dataset,
# we can directly move to visualization.

# Define some genes of interest for the visualization
genes_of_interest = ['IL7R', 'CD3G', 'CD8A', 'GNLY', 'NKG7', 'KLRB1', 'CD14', 'LYZ', 'FCGR3A', 'MS4A1']

# Check if the genes of interest are in the dataset
assert all(gene in adata.var_names for gene in genes_of_interest), "Not all specified genes are found in the dataset."

# Create the dotplot
# Grouping by cluster annotations assuming `adata.obs['louvain']` as the annotation
sc.pl.dotplot(adata, var_names=genes_of_interest, groupby='louvain', use_raw=False)
```

### Explanation:

1. **Import Scanpy**: This is needed for processing and visualization.
2. **Load Dataset**: `sc.datasets.pbmc3k_processed()` loads the processed PBMC dataset from 10x Genomics. This dataset is handy for demonstrations and comes pre-loaded with cluster annotations, gene filters, and some normalization.
3. **Define Genes of Interest**: These are the genes you want to focus on in your dotplot. Modify this list based on your research focus.
4. **Create Dotplot**: Using the `sc.pl.dotplot` function, the data is visualized. The genes specified are plotted against clusters identified (`groupby='louvain'`). `use_raw=False` uses the processed data as opposed to raw count data.

Just run the code to visualize the expression of the chosen genes across different cell clusters identified in the dataset. The assumptions include the dataset having Louvain cluster assignments already performed, and genes listed are already filtered and relevant in this context.

Remember, for a different dataset or different stages of preprocessing, you might need to adjust the steps, including normalizing the data or re-running clustering. This script assumes that such steps are already completed in the `pbmc3k_processed` dataset.
"""

import scanpy as sc

# Load the example dataset
adata = sc.datasets.pbmc3k_processed()

# Typically preprocessing would be done here, but since we're using a processed dataset,
# we can directly move to visualization.

# Define some genes of interest for the visualization
genes_of_interest = ['IL7R', 'CD3G', 'CD8A', 'GNLY', 'NKG7', 'KLRB1', 'CD14', 'LYZ', 'FCGR3A', 'MS4A1']

# Check if the genes of interest are in the dataset
assert all(gene in adata.var_names for gene in genes_of_interest), "Not all specified genes are found in the dataset."

# Create the dotplot
# Grouping by cluster annotations assuming `adata.obs['louvain']` as the annotation
sc.pl.dotplot(adata, var_names=genes_of_interest, groupby='louvain', use_raw=False)

"""### Note: the error `AssertionError: Not all specified genes are found in the dataset.` comes because that gpt writes a codeline with asserting its given gene list exist in the built-in dataset.

---
### Example11: Tracksplot visualization

### Prompt

Provide the python code for visualizing the genes expression values through tracksplot with the API only from Scanpy. Apply it to the built-in pbmc3k processed dataset.


### GPT-4 Turbo Answer:

To create a genes expression visualization using a tracks plot for the `pbmc3k` dataset using the Scanpy API, you'll first need to load the dataset, preprocess it as necessary, and then use the `sc.pl.tracksplot` function to generate the plot. Below I'll guide you through the complete process, including necessary preprocessing steps like normalization, principal component analysis, and computing the neighborhood graph, which are typical for single-cell RNA-seq data analysis.

First, you need to ensure that you have Scanpy installed in your Python environment. If it's not installed, you can install it using pip:

```bash
pip install scanpy
```

Now, here's a complete example of how to handle the pbmc3k dataset and visualize specific gene expressions with tracksplot:

```python
import scanpy as sc

def main():
    # Load the example dataset
    adata = sc.datasets.pbmc3k_processed()

    # Perform necessary preprocessing if it was not already done
    sc.pp.normalize_total(adata, target_sum=1e4)
    sc.pp.log1p(adata)
    sc.pp.highly_variable_genes(adata, n_top_genes=2000)
    sc.pp.scale(adata, max_value=10)
    sc.pp.pca(adata, n_comps=50)
    sc.pp.neighbors(adata)
    sc.tl.umap(adata)

    # Perform clustering (optional but useful for tracksplot)
    sc.tl.louvain(adata)

    # Visualization: Select few genes of interest
    genes_to_plot = ['IL7R', 'CD79A', 'MS4A1', 'CD8A', 'CD14', 'LYZ', 'FCGR3A', 'MS4A7']

    # Check if the genes are in the dataset
    genes_to_plot = [gene for gene in genes_to_plot if gene in adata.var_names]

    if not genes_to_plot:
        print("None of the specified genes were found in the dataset.")
        return

    # Create the tracks plot
    sc.pl.tracksplot(adata, var_names=genes_to_plot, groupby='louvain')

if __name__ == "__main__":
    main()
```

### Explanation:
1. **Data Loading**: We load the processed version of the `pbmc3k` dataset directly from Scanpy's dataset collection. This dataset has been pre-processed including normalization and log-transformation.

2. **Check and Preprocess (if necessary)**: Though `sc.datasets.pbmc3k_processed()` generally contains a preprocessed dataset, the code snippet includes checks and preprocessing steps to ensure all necessary preprocessing has been done. This includes normalization, logarithmic transformation, selection of highly variable genes, scaling, PCA, computation of neighborhood graphs, UMAP for dimension reduction, and clustering using the Louvain algorithm.

3. **Gene Selection**: You can customize `genes_to_plot` with the genes you are interested in visualizing.

4. **Tracks Plot**: The `sc.pl.tracksplot` function generates a tracks plot. Here, it is grouped by the Louvain clusters which categorizes the cells into different clusters.

Make sure that the gene names specified in `genes_to_plot` are correctly named and present in the dataset. You can adjust the list of genes based on your specific genes of interest for the PBMC dataset. This code will run in any standard Python environment where Scanpy is installed.
"""

import scanpy as sc

def main():
    # Load the example dataset
    adata = sc.datasets.pbmc3k_processed()

    # Perform necessary preprocessing if it was not already done
    sc.pp.normalize_total(adata, target_sum=1e4)
    sc.pp.log1p(adata)
    sc.pp.highly_variable_genes(adata, n_top_genes=2000)
    sc.pp.scale(adata, max_value=10)
    sc.pp.pca(adata, n_comps=50)
    sc.pp.neighbors(adata)
    sc.tl.umap(adata)

    # Perform clustering (optional but useful for tracksplot)
    sc.tl.louvain(adata)

    # Visualization: Select few genes of interest
    genes_to_plot = ['IL7R', 'CD79A', 'MS4A1', 'CD8A', 'CD14', 'LYZ', 'FCGR3A', 'MS4A7']

    # Check if the genes are in the dataset
    genes_to_plot = [gene for gene in genes_to_plot if gene in adata.var_names]

    if not genes_to_plot:
        print("None of the specified genes were found in the dataset.")
        return

    # Create the tracks plot
    sc.pl.tracksplot(adata, var_names=genes_to_plot, groupby='louvain')

if __name__ == "__main__":
    main()

"""### Note: this generated code contains 2 issues. The first issue is generated by `scanpy.pp.highly_variable_genes`, which is `TypeError: putmask: first argument must be an array`. The second issue is due to `scanpy.pp.pca`, which is `ValueError: Input X contains NaN.`.

### Example 12: Stacked violin ranking visualization

### Prompt

Provide the python code for visualizing the ranking of genes expression values through stacked violin figure with the API only from Scanpy. Apply it to the built-in pbmc3k processed dataset.

### GPT-4 Turbo Answer:

Below, I provide a Python code snippet to visualize the ranking of gene expression values using a stacked violin plot utilizing the Scanpy API. This snippet applies to the built-in "pbmc3k_processed" dataset in Scanpy. Before running this script, make sure you have installed the necessary packages (`scanpy`, `anndata`, and related dependencies) in your Python environment.

```python
import scanpy as sc

# Load built-in pbmc3k dataset processed version
adata = sc.datasets.pbmc3k_processed()

# List of genes to plot: here we select a few genes as an example
genes_to_plot = ['IL7R', 'CD79A', 'CD3D', 'CD8A', 'LYZ']

# Stacked violin plot of selected genes
sc.pl.stacked_violin(adata, var_names=genes_to_plot, groupby='louvain', swap_axes=True,
                     title='Gene Expression Ranking in PBMCs')

# Show the plot
sc.pl.show()
```

### Explanation

1. **Importing Scanpy**: We first import Scanpy, which is a widely-used library for single-cell analysis.

2. **Loading Data**: We load the 'pbmc3k_processed' dataset directly from Scanpy's datasets. This dataset is preprocessed, including normalization and clustering, representing a typical workflow result.

3. **Gene Selection**: Here, a list `genes_to_plot` is defined containing the gene names for which the expression is to be visualized. You may modify this list based on the genes of interest or focus on top expressed genes identified via previous analysis.

4. **Stacked Violin Plot**: The `sc.pl.stacked_violin` function is used to create the plot. Important parameters include:
   - `var_names`: Names of the variables or genes.
   - `groupby`: The category over which to group the data, here the `louvain` clustering results.
   - `swap_axes`: With this set to True, genes become rows and categories become columns, which might fit better for presentations depending on the plot's orientation preference.
   - `title`: Setting up the title of the plot.

5. **Display the Plot**: `sc.pl.show()` is used to render the plot, although this is optional in most environments as plots are displayed automatically by default.

Make sure that the gene names used in `genes_to_plot` should exist within the dataset. You can check the genes available in your dataset using `adata.var_names` to customize the `genes_to_plot` list further.
"""

import scanpy as sc

# Load built-in pbmc3k dataset processed version
adata = sc.datasets.pbmc3k_processed()

# List of genes to plot: here we select a few genes as an example
genes_to_plot = ['IL7R', 'CD79A', 'CD3D', 'CD8A', 'LYZ']

# Stacked violin plot of selected genes
sc.pl.stacked_violin(adata, var_names=genes_to_plot, groupby='louvain', swap_axes=True,
                     title='Gene Expression Ranking in PBMCs')

# Show the plot
sc.pl.show()

"""### Note: the generated code has already finished the task. However, it treats scanpy.pl.stacked_violin as rendering figure, and think it should call API like `plt.show()` to show the figure. But it uses `scanpy.pl.show()` hallucinately, which is not an API from scanpy."""